### ISSUE TITLE
Chrome issue.

### ISSUE THREAD

**Issue by rburawes** [web-push-libs/webpush-java#1]
Hi Martin,

Thank you for this library.  I've successfully run this project and I can see that the notifications are being delivered to Firefox and Chrome.  I've just noticed that the payload has an issue with Chrome, the data in PushEvent is always null while in Firefox everything is ok.  Is there any modification that I need to do in for the payload to be delivered in Chrome clients too?

Cheers,

Rae

**Comment by martijndwars** [comment]
Hi Rae,

Thanks for opening the issue! Chrome did not support payload until version 50 which came out in April (my last commit was made before that). I need to investigate Chrome's support (it's explained really well [here](https://developers.google.com/web/updates/2016/03/web-push-encryption)) and check what is going wrong.

Martijn

**Comment by rburawes** [comment]
Thank you for replying, if not mistaken the missing part of the implementation is the 'auth' must be used in creating PRK based on the link that you've given above.  I'll try to figure this out.  This library that you've created will help a lot of Java developers working on the same issue especially those new to encryption stuffs like me.

**Comment by martijndwars** [comment]
I refactored the code in the [chrome](https://github.com/MartijnDwars/web-push/tree/chrome) branch. It works in Firefox and Chrome and allows payloads. I'll merge this into master and release to Maven Central next week.

**Comment by martijndwars** [comment]
Merged into master and released to Maven. Please open a new issue if there is still a problem.

**Comment by rburawes** [comment]
This is tested, everything works fine now. Thank you.
