### ISSUE TITLE
Web push in Android WebView

### ISSUE THREAD

**Issue by rrjanbiah** [web-push-libs/webpush-java#142]
Apologies, if this is a wrong place or answered somewhere...

Since, Android WebView doesn't support web push yet, can this library be used to provide that feature?

**Comment by martijndwars** [comment]
Note that this library implements the server-side functionality, i.e. sending a push notification to the push service. This assumes that the browser (or Android WebView) has already created a push subscription first and has sent the subscription to the server. See [Usage Example](https://github.com/web-push-libs/webpush-java/wiki/Usage-Example) for an explanation of this flow.

As for Android WebView, [this](https://blog.pushpad.xyz/2018/04/can-i-use-the-web-push-api-with-hybrid-mobile-apps/) blog post by Marco Collin in 2018 mentions that Android WebView does not implement the Push API. Judging from [this](https://bugs.chromium.org/p/chromium/issues/detail?id=421921) Chromium ticket that is still the case as I'm writing this. If your client cannot create a push subscription, then this library cannot help you either.

**Comment by rrjanbiah** [comment]
@MartijnDwars Thanks for the note
