### ISSUE TITLE
not able to make push notifications pop up on screen of android phone

### ISSUE THREAD

**Issue by manuel-ch** [web-push-libs/webpush-java#174]
see my post on SO: https://stackoverflow.com/questions/67862991/progressive-web-app-pwa-not-able-to-make-push-notifications-pop-up-on-screen-o

is this a known limitation of web push compared to native apps?

**Comment by martijndwars** [comment]
From your post on SO:

> After some research, i found out that native android apps need to add "notification channels" (feature added with android oreo) to be able to set the app's notification setting to "sound and pop-up" (pop up may also be called heads-up) instead of only "sound". For PWA, i can not find any information about such options.
> 
> In the android notification settings of my (installed) PWA, there is one category called "General", Setting is sound only, pop-up / heads-up is not activated. When i activate it, the notifications pops up as expected.

I think you answered your question yourself already. Android apps need to be granted a permission to show a popup, and unless you grant this permission, you won't see a popup. This is a limitation of the Android ecosystem, not of the Web Push protocol or this library.

**Comment by manuel-ch** [comment]
Hi Martin

 

Thanks for your answer, could you add it to SO post  https://stackoverflow.com/questions/67862991/progressive-web-app-pwa-not-able-to-make-push-notifications-pop-up-on-screen-o?

 

There are some other posts piling up on SO so your answer may be welcome!

 

Thanks!

Manuel

 

Von: Martijn Dwars ***@***.***> 
Gesendet: Freitag, 11. Juni 2021 12:57
An: web-push-libs/webpush-java ***@***.***>
Cc: manuel-ch ***@***.***>; Author ***@***.***>
Betreff: Re: [web-push-libs/webpush-java] not able to make push notifications pop up on screen of android phone (#174)

 

From your post on SO:

After some research, i found out that native android apps need to add "notification channels" (feature added with android oreo) to be able to set the app's notification setting to "sound and pop-up" (pop up may also be called heads-up) instead of only "sound". For PWA, i can not find any information about such options.

In the android notification settings of my (installed) PWA, there is one category called "General", Setting is sound only, pop-up / heads-up is not activated. When i activate it, the notifications pops up as expected.

I think you answered your question yourself already. Android apps need to be granted a permission to show a popup, and unless you grant this permission, you won't see a popup. This is a limitation of the Android ecosystem, not of the Web Push protocol or this library.

**Comment by martijndwars** [comment]
I'll add a comment after my vacation. Feel free to copy my answer to StackOverflow if you have the opportunity.
