### ISSUE TITLE
Getting 406 status code - Not Acceptable

### ISSUE THREAD

**Issue by jclarkk** [web-push-libs/webpush-java#175]
Hi,

In the past couple of days, I'm getting status code 406 after sending the push notification.

AFAIK, 406 occurs when the server is not capable of producing the content type that is required by the client. For instance, if the client tells the server that it accepts only 'application/json' and the server would like to reply with plain text then an issue such as the above would occur.

Could this be a symptom for something else? Perhaps Google API is trying to reply with an error text and the library is expecting a JSON.

**Comment by martijndwars** [comment]
> In the past couple of days, I'm getting status code 406 after sending the push notification.

One week later; is this still an issue?

**Comment by jclarkk** [comment]
Seems to have been resolved from yesterday. Thanks.
