### ISSUE TITLE
How to install in Eclipse?

### ISSUE THREAD

**Issue by rarahim75** [web-push-libs/webpush-java#176]
How to install this library in Eclipse if i'm not using gradle nor maven?

**Comment by martijndwars** [comment]
You would have to manually collect and download the dependency (and all its transitive dependencies) from Maven Central and add them to your project's classpath in Eclipse (see e.g. [this StackOverflow question](https://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse)). I would strongly recommend using Maven or Gradle though; manually managing dependencies is a pain.
