### ISSUE TITLE
Update VAPID Support to meet spec

### ISSUE THREAD

**Issue by comp615** [web-push-libs/webpush-java#18]
https://tools.ietf.org/html/draft-ietf-webpush-vapid-01

They changed the format of the Authorization header. Looks like it should now be "WebPush aklsjdalksjdlkajsf" instead of Bearer.

Also according to this: https://developers.google.com/web/updates/2016/07/web-push-interop-wins crypto-key claims should be comma separated instead of semi-colon.

**Comment by martijndwars** [comment]
Thanks for the heads up! I'll update and check browser compatibility in the following days. The semicolon, for instance, was necessary for Chrome (due to a bug Chrome only supported semicolons, and all other browser vendors accepted semicolon as well, though it is non-standard).

**Comment by bschlief** [comment]
I was wondering how this issue was progressing.

**Comment by martijndwars** [comment]
I changed the Authorization header to "WebPush .." instead of "Bearer .." I have not yet replaced the semi-colon by a comma. The change is easy to make, but I've not given it much priority.

May I ask, is this issue preventing you from using the library?

**Comment by bschlief** [comment]
I haven't been able to send a VAPID push yet, and I thought perhaps this was the issue. I keep getting a response code of 400 with `Unauthorized Registration` as the message. I'll go double check everything and get back to you.

Thanks for the library and the quick response!

**Comment by ilanov** [comment]
Is this issue solved?
I'm using v2.0.0 (taken from maven repository) and while trying to send a push notification from my application server I get 400 with Unauthorized Registration. It works fine when pushing to chrome via https://web-push-codelab.appspot.com/.
I'll appreciate your response.

**Comment by martijndwars** [comment]
The issue hasn't been resolved completely, but I doubt it is the cause of your error. I currently do not have the time to look into this. Over the next week, I'll setup a demo website to test whether everything still works.

**Comment by bschlief** [comment]
@ilanov: Hi, I had an unexpected 400 with `Unauthorized Registration` problem too, which I had filed here: https://github.com/MartijnDwars/web-push/issues/20

In the end, creating the vapid keys using the openssl binary allowed my pushes to be accepted. Try that instead of one that you may have created via JS, and see if that helps. I was super surprised that it seemed to matter, but it has. I've since tried 6 more keys created via JS, and had no luck, but the openssl ones have been fine. I haven't had time yet to figure out what the difference could be.

**Comment by ilanov** [comment]
Thanks a lot bschlief.
It works like a charm!

**Comment by abhisheksahani** [comment]
@bschlief i am also facing the same issue when i am using the vapid keys generated with node code in my java server i am getting 400 . can u please specify how to generate the vapid keys using open ssl

**Comment by bschlief** [comment]
@abhisheksahani The vapid usage docs sheet in this repo describes it beautifully:

https://github.com/MartijnDwars/web-push/blob/master/doc/VAPID.md#generate-a-keypair
