### ISSUE TITLE
response body is null in chrome push

### ISSUE THREAD

**Issue by manindrMBK** [web-push-libs/webpush-java#19]
i am trying to use your new method of sending push using httppost, but the httpresponse is giving status code as 201 and body as null.
However when i use old way (using request and async) it gives proper response. Can you please help me with this?

Thanks

**Comment by martijndwars** [comment]
Hi @manindr!

The HTTP 201 status code indicates "Created", i.e. it is a way for the push service to indicate that the push message has been accepted. Hence, a 201 response is expected and correct behaviour. I believe the body is also meant to be empty. The push service will then deliver the message to the user agent. Are you not receiving the push message at the user agent? If this is the case, have you configured your service worker correctly? What is, according to you, the proper response?

**Comment by manindrMBK** [comment]
Yes, i am receiving the notification. so this means that instead of response body i can use status code for result verification.

thanks for the explanation

**Comment by martijndwars** [comment]
You're welcome!
