### ISSUE TITLE
Unable to send web pushes: receive 400 - Unauthorized Registration

### ISSUE THREAD

**Issue by bschlief** [web-push-libs/webpush-java#20]
I have a web app that is able to register subscriptions and send web pushes to chrome and firefox using node, but when I try to use those subscriptions with this library in java, I am getting `Unauthorized Registration`.

My test is below, which is modeled on [this test](https://github.com/MartijnDwars/web-push/blob/master/src/test/java/nl/martijndwars/webpush/PushServiceTest.java#L61-L87) in the web-push repo.

If you have any ideas about how I could be screwing this up, I'd be much obliged. 

    @Test
    public void testPushChromeVapid() throws Exception {
        String endpoint = "https://fcm.googleapis.com/fcm/send/eKUKTbHcFbQ:APA91bFzJMkNQO1xHc2-JVcRRa4I76yKR9o4IvgJBx1eIyF1EordVbWbpyD5pxMZJfbjnmPo_EGU8yCATZbeypc2_hMZE3GutdJGqqFdjht7PhhaIGg2IwRdRtH8r0lSRK0wAN8bD00O";

        // Base64 string user public key/auth
        String userPublicKey = "BF1xKcbEKKydzY72hHTZOdlrGCK1OE2DLgcTA_qzOejXCAuPmP87MKgEVwaGsYjpbSIUyG2E4GxZYF74lWXG04w=";
        String userAuth = "tRoRvuq0UZqzbT0lv3r3Cw==";

        // Base64 string server public/private key
        String vapidPublicKey = "BDML-FghkuCdr0U1AlPHycUDlmAio4xL2OeX2oC_-X1ArOWdqzFea2_h3pyqxvl2x633Y-RR7hWbpbCmP73qn58";
        String vapidPrivateKey = "<redacted>";

        // Construct notification
        Notification notification = new Notification(endpoint, userPublicKey, userAuth, getPayload());

        // Construct push service
        PushService pushService = new PushService();
        pushService.setSubject("mailto:bschlief@gmail.com");
        pushService.setPublicKey(Utils.loadPublicKey(vapidPublicKey));
        pushService.setPrivateKey(Utils.loadPrivateKey(vapidPrivateKey));

        // Send notification!
        HttpResponse httpResponse = pushService.send(notification);

        System.out.println(httpResponse.getStatusLine().getStatusCode());
        System.out.println(IOUtils.toString(httpResponse.getEntity().getContent(), StandardCharsets.UTF_8));
    }

A very similar attempt with a valid firefox subscription results in a 401 with a mozilla error code about a problem with the authorization header.

    {
        "code": 401,
        "errno": 109,
        "error": "Unauthorized",
        "message": "Request did not validate Invalid Authorization Header",
        "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes"
    }

**Comment by martijndwars** [comment]
Thanks for getting in touch. I don't have the time to look into this right now, but I'll try to look into it this weekend.

**Comment by bschlief** [comment]
Awesome, I'll be around this weekend to answer any questions you might have as well. Thanks again.

**Comment by bschlief** [comment]
Let me know if there's anything I can do to help track this down.

**Comment by martijndwars** [comment]
Sorry, I didn't get to debugging this. Question: how did you request the subscription on the client side? I'm wondering if the public key that you used to request the subscription matches the key pair you use on the server side. I assume you followed [these](https://github.com/MartijnDwars/web-push/blob/master/doc/VAPID.md#client-side) instructions?

**Comment by bschlief** [comment]
The methodology for creating the VAPID keys is per https://github.com/web-push-libs/web-push/#command-line

Here's a sample freshly created sample of the sort of key we're getting.

    16:02:49-bryanschlief~$ npm install web-push -g
    /usr/local/bin/web-push -> /usr/local/lib/node_modules/web-push/src/cli.js
    /usr/local/lib
    └─┬ web-push@3.2.1
      ├─┬ asn1.js@4.9.0
      │ ├── bn.js@4.11.6
      │ ├── inherits@2.0.3
      │ └── minimalistic-assert@1.0.0
      ├── http_ece@0.5.2
      ├─┬ jws@3.1.4
      │ ├── base64url@2.0.0
      │ ├─┬ jwa@1.1.5
      │ │ ├── buffer-equal-constant-time@1.0.1
      │ │ └── ecdsa-sig-formatter@1.0.9
      │ └── safe-buffer@5.0.1
      ├── minimist@1.2.0
      └── urlsafe-base64@1.0.0

    16:02:57-bryanschlief~$ web-push generate-vapid-keys --json
    {"publicKey":"BMzvZylzxhzL7LmFSW7Swj7GGariKK7WAWbk-Q2ESt1apjR2Ek9Rb1tfLSwoli3ww4IUfIlR1-VWATH1tAFJCBw","privateKey":"tZ9kly49ai8KYQQU_11mVSk6VLjzUSHK-xH6vgncKak"}


Here's a sample minimal JS that we're using to create a subscription (using the freshly generated keypair above):

    const vapidPublicKey = 'BMzvZylzxhzL7LmFSW7Swj7GGariKK7WAWbk-Q2ESt1apjR2Ek9Rb1tfLSwoli3ww4IUfIlR1-VWATH1tAFJCBw'

    function register () {
      if (!navigator.serviceWorker) return
      navigator.serviceWorker.register('push-worker.js')
      .then(registration => {

        return registration.pushManager.getSubscription()
          .then(subscription => {

            if (subscription) {
              return subscription
            }

            return registration.pushManager.subscribe({
                userVisibleOnly: true,
                applicationServerKey: urlBase64ToUint8Array(vapidPublicKey)
              }
            )
          })
      }).then(subscription => {
        console.log(subscription)
      })
    }

    function urlBase64ToUint8Array (base64String) {
      const padding = '='.repeat((4 - base64String.length % 4) % 4)
      const base64 = (base64String + padding)
        .replace(/\-/g, '+')
        .replace(/_/g, '/')

      const rawData = window.atob(base64)
      const outputArray = new Uint8Array(rawData.length)

      for (let i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i)
      }
    }

---> Registration in JS using new keypair creates this subscription

    subscription:
    { endpoint: 'https://fcm.googleapis.com/fcm/send/dLrb97aSFhg:APA91bFBFLNas-R33frcm6CRPOQWzIrOknsmQmvZLNLsoLuzach8lNF3nYPD7SKljznS9Fxc7oB5R9VfsVWeMXjcTy8KrQQ5pAx5XPeMFeMgPjwg8K_S60edodd2D2OBve3Oq5hQvaFx',
     keys:
      { p256dh: 'BORZi3TTCZbVQ7ReaBah6tCNRyr_ooxowjpjXuS0DOxMMtZ8vg__46do3cS8ky-vMjVRTGCIcMau79HNzra1u0A=',
        auth: 'xhvMLfKDkwZ0CR_kb_adKw==' } }


I can send to this subscription successfully using the web-push JS library (https://github.com/web-push-libs/web-push/).

Here's the matching Java test that result in a 400 with Unauthorized Registration

    @Test
    public void testPushChromeVapid() throws Exception {
        String endpoint = "https://fcm.googleapis.com/fcm/send/dLrb97aSFhg:APA91bFBFLNas-R33frcm6CRPOQWzIrOknsmQmvZLNLsoLuzach8lNF3nYPD7SKljznS9Fxc7oB5R9VfsVWeMXjcTy8KrQQ5pAx5XPeMFeMgPjwg8K_S60edodd2D2OBve3Oq5hQvaFx";

        // Base64 string user public key/auth
        String userPublicKey = "BORZi3TTCZbVQ7ReaBah6tCNRyr_ooxowjpjXuS0DOxMMtZ8vg__46do3cS8ky-vMjVRTGCIcMau79HNzra1u0A=";
        String userAuth = "xhvMLfKDkwZ0CR_kb_adKw==";

        // Base64 string server public/private key
        String vapidPublicKey = "BMzvZylzxhzL7LmFSW7Swj7GGariKK7WAWbk-Q2ESt1apjR2Ek9Rb1tfLSwoli3ww4IUfIlR1-VWATH1tAFJCBw";
        String vapidPrivateKey = "tZ9kly49ai8KYQQU_11mVSk6VLjzUSHK-xH6vgncKak";

        JSONObject jsonObject = new JSONObject();
        jsonObject.append("title", "Hello");
        jsonObject.append("message", "World");

        // Construct notification
        Notification notification = new Notification(endpoint, userPublicKey, userAuth, jsonObject.toString().getBytes());

        // Construct push service
        PushService pushService = new PushService();
        pushService.setSubject("mailto:bschlief@gmail.com");
        pushService.setPublicKey(Utils.loadPublicKey(vapidPublicKey));
        pushService.setPrivateKey(Utils.loadPrivateKey(vapidPrivateKey));

        // Send notification!
        HttpResponse httpResponse = pushService.send(notification);

        System.out.println(httpResponse.getStatusLine().getStatusCode());
        System.out.println(IOUtils.toString(httpResponse.getEntity().getContent(), StandardCharsets.UTF_8));
    }

Here's a gist of the output: https://gist.github.com/bschlief/7416ee659dd84d06c2d49e6ca98632d0

**Comment by bschlief** [comment]
So, on the recommendation of a brilliant coworker, I recreated the vapid keypair using methodology @MartijnDwars recommended explicitly : 

https://gist.github.com/bschlief/0665d45c0368dcd5d7344221c1f6aa94

And those keys worked like a charm. So i'm closing this.

(here's the test I used that worked: https://gist.github.com/bschlief/3327c209bbe10dfd6cd79060b6ce78b7)

@MartijnDwars, I don't know if you have a digital tip jar anywhere, but I'd sure love to buy you a beverage/meal. Thanks again.

**Comment by martijndwars** [comment]
I'm happy you fixed it! It's still strange that keys generated by the JS lib don't work (keys should be independent of the tool that generated them). Hopefully this issue can help others until I've discovered what's causing this issue. Cheers!

**Comment by bschlief** [comment]
I was also super surprised. If you need any more data in the future, I'm happy to help.

**Comment by pradeepprajapat** [comment]
@bschlief I am implementing push notification using web push lib in javascript and java. When I test application with https://web-push-codelab.appspot.com/ notifications works fine. But same keys as on https://web-push-codelab.appspot.com/ are not working if I am generating notification from java code.

I also tried using VAPID keys generated by openssl as described above, still getting error: 400, unauthorized header .
Could you please help me?

**Comment by martijndwars** [comment]
Most likely, the keys you're seeing on https://web-push-codelab.appspot.com/ are encoded differently. If you need assistance, please open a new issue so we can keep discussions separated.

**Comment by pradeepprajapat** [comment]
I generated keys using openssl, and restarted application several times. It solved the issue. Thank you @MartijnDwars  for your help.
