### ISSUE TITLE
vapid 

### ISSUE THREAD

**Issue by abhisheksahani** [web-push-libs/webpush-java#22]
for vapid do we need any license for commercial use

**Comment by martijndwars** [comment]
VAPID (Voluntary Application Server Identification for Web Push) is a protocol by which an application server can voluntarily identify itself to a push service. There's no license associated to the use of VAPID.

**Comment by abhisheksahani** [comment]
if i use vapid for web push notification then should server also register to fcm and get gcm key for sending web push notification

**Comment by martijndwars** [comment]
No, when using VAPID, there is no need to register the server upfront.
