### ISSUE TITLE
Decrypting Web Push Payload 

### ISSUE THREAD

**Issue by abhisheksahani** [web-push-libs/webpush-java#24]
Hi Martin,

so my use case i want to decrypt the webpush payload for automation. I have all keys server public private , and client p256dh and auth . how i will do that

**Comment by martijndwars** [comment]
Note the following sequence of events:

1. The payload is encrypted on the server (by this library) and sent to the push service (e.g. Mozilla's Push Service).
2. The push service delivers the _encrypted_ payload to the browser.
3. Pushed messages are authenticated and decrypted by the browser before delivery to applications [[1]](https://tools.ietf.org/html/draft-ietf-webpush-protocol-01#page-6). The browser uses the private key to decrypt the message and invokes the JavaScript handler, passing it the _decrypted_ message.

As such, there is no need to decrypt messages yourself.

**Comment by abhisheksahani** [comment]
that i know , in my use case i am not sending the push to chrome server (i am not hiting fcm api) , instead i am sending push to dummy server which is acting like chrome server now in that dummy server i want to decrypt the message .

**Comment by martijndwars** [comment]
Ah, I get your question. I'm sorry, but I have no experience on decrypting the message.

**Comment by jedi7** [comment]
@abhisheksahani Did you found, how to decrypt it?

**Comment by thewyolar** [comment]
Has anyone found a solution? How to decrypt web push payload?
