### ISSUE TITLE
Why is Async removed in this commit?

### ISSUE THREAD

**Issue by Cyril-Engels** [web-push-libs/webpush-java#25]
I saw that in this commit you removed Async request. 
https://github.com/MartijnDwars/web-push/commit/4737ed8b99a7a1a7cd5bf04e25fcf1082380fc7d

Could you please explain a little bit why it is removed? Thanks!

**Comment by martijndwars** [comment]
The Async API was a bit harder to use (especially during debugging, when I had to inspect the output) and I wasn't sure anyone benefitted from the async part. If you want, I can refactor this in the next release?

**Comment by Cyril-Engels** [comment]
That's true. 
Synchronous is fine. It's probably better for batching requests to multiple users with Async. 
But if you are free to do the refactor, that would be great.
Thanks!
