### ISSUE TITLE
Send data containing UTF-8 characters

### ISSUE THREAD

**Issue by gvieiradot** [web-push-libs/webpush-java#27]
When I try to send a notification (using VAPID) with a payload that contains some UTF-8 characters like 'ç', the notification is sent and received by the end user, but with no data.

All the rest is working perfectly.

Thanks!

**Comment by martijndwars** [comment]
Thanks for creating the issue! That's a serious bug, but it should not be too hard to fix. I'll try to fix this over the weekend.

**Comment by martijndwars** [comment]
Are you sure the problem is with UTF-8 characters? I.e. does a message without UTF-8 characters arrive correctly? Which browser were you using?

I just tried sending a push message with `ç` and the browser received the message successfully (tested with the stable, beta, and unstable versions of Chrome and Firefox).

**Comment by gvieiradot** [comment]
Chrome version: 58.0.3029.110. (Desktop)
Yes, without `ç ã é..` characters the message data is sent.
With one or more utf-8 char the message is sent, but no data.
This is some of the messages I'm trying to send (Json string): `{"tag":"declined","reason":"Endereço não encontrado."}`

**Comment by martijndwars** [comment]
I changed the Selenium tests to use your example as a payload (84096d96b2daed7266dcb95f731622a24c52b58e). Travis is running this against Chrome 58, 59, 60 [now](https://travis-ci.org/MartijnDwars/web-push/builds/234377544). I suspect that there's an external variable (e.g. default charset) that is different on your system. I'll need to dig a bit deeper to see what's going wrong.

**Comment by gvieiradot** [comment]
I'll make a test later to try to isolate the problem.
I'll post the result.

**Comment by gvieiradot** [comment]
Yep, you're right!
Tested on my linux server, the data is sent!
On my PC don't..
It's a Windows 7, JDK 1.8, lang pt-br;
Anyways thanks for the help!
