### ISSUE TITLE
http wrapper

### ISSUE THREAD

**Issue by bohdaq** [web-push-libs/webpush-java#34]
Hey @MartijnDwars,

I've made a [small http wrapper](https://github.com/bohdaq/Web-Push-Microservice) over your library for own needs, but thought it may be useful for other folks.

Cheers,
Bogdan

**Comment by martijndwars** [comment]
Hey!

Cool to see that people are building stuff on top of this library! Also good to see that you got everything working (e.g. configuring BouncyCastle, generating and encoding the keypair, using the API). Was it a hassle to set this up/were the instructions clear enough?

Cheers,

Martijn

**Comment by bohdaq** [comment]
Martijn,

I was using [this tutorial](https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/) to get it running, also found one issue about [missing function declaration](https://github.com/GoogleChrome/push-notifications/issues/46). 

It took me some time to understand all technical details, but then all became clear.

So far everything works pefectly
