### ISSUE TITLE
Service workers Push event is not triggering 

### ISSUE THREAD

**Issue by David740** [web-push-libs/webpush-java#38]
I have used the same API and procedure to sent notification , I am able to send notification successfully with response code 200, but still push event is not happening on receiving notification. 

` {
  auth:"hcQQq+1FeDuSu7V0zd5DXA==" 
  endpoint:"https://fcm.googleapis.com/fcm/send/
  cXgp0l3svNo:APA91bG8dDfZhrc0iaSyzvuV1BvnxXz9T-
  SmLCKOymKrEdwvrh0_SjzjnU3ORRKvW5QD-
  Zp196T5nAGPayR7EKu_Bkb0pQrSex7Q3DZSu54Lo83AEiUE6p-2Xn-nrquCymKVFt6Z4nY8"
  key:"BJv2qC3WSCsRszMi57vOBpFjnIpdJ/
  uXQQFj4d0XZD9lRuZKuBgJNVFra0SFEvRlQQ88eG8RWWs7sSvO9Pbdkwk="
  }`
above given is my endpoint in which i am sending notification.

**Comment by eastflag** [comment]
I also hava the same issue.
Status code return 201 but notification is not happing on the phone.
So I set up node server by using the same code.
After node server return ok, notification happen succeffuly on th phone.

**Comment by fima-taf** [comment]
Did you resolved it in anyway? Because i am having the same issue (with 201 at java, but the 'push' event is not triggered.

**Comment by martijndwars** [comment]
Could you try https://github.com/MartijnDwars/spring-boot-web-push? The README contains instructions on how to configure the keys. The project contains a frontend that allows you to click a button, after which a notification is sent to the browser vendor, which in turn sends the notification to the browser. I've used this example in the past, so I'm confident that it works.

If this example works for you, then that would indicate a problem in your code, and maybe you can use it to narrow down the problem.

**Comment by fima-taf** [comment]
My problem was that i've passed the wrong key for each call, everything is working perfectly now, thx anyway.

**Comment by martijndwars** [comment]
Ok, thanks for letting me know 👍 I'll close this issue then!
