### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by staticdkk** [web-push-libs/webpush-java#44]
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_151 contains a valid JDK installation 
I use java 8

**Comment by martijndwars** [comment]
This is a problem with your Java installation and unrelated to this library. I see you're using JRE, but I expect you need the JDK to compile a Java program. Perhaps [this](https://stackoverflow.com/questions/11345193/gradle-does-not-find-tools-jar) post helps.

**Comment by staticdkk** [comment]
thank you MartijnDwars
