### ISSUE TITLE
NoSuchProviderException for "BC"

### ISSUE THREAD

**Issue by johanvs** [web-push-libs/webpush-java#48]
Hello,
When instanciating a PushService object, the line KeyFactory.getInstance("ECDH", "BC") in Utils.class throws a NoSuchProviderException for "BC".
Is it normal ?
Thanks.

**Comment by johanvs** [comment]
Ok so as advised in [this post of stackoverflow](https://stackoverflow.com/questions/3711754/why-java-security-nosuchproviderexception-no-such-provider-bc) I added BouncyCastle as a security provider by adding : `Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());` before the creation, and now it works.

**Comment by martijndwars** [comment]
Yes, that is indeed necessary. I'll reopen the issue so we can add this to the README.md.
