### ISSUE TITLE
aes128gcm content encoding / MS Edge support

### ISSUE THREAD

**Issue by ghys** [web-push-libs/webpush-java#53]
Hi,
I tested sending a notification to MS Edge - already working in Chrome and Firefox - without success: the push server (`https://db5.notify.windows.com/w/?token=...`)  returns 400 Bad Request with no body.

After a quick check and according to https://github.com/web-push-libs/web-push-php/releases/tag/v4.0.0 it _appears_ to be because it requires the `aes128gcm` content encoding, `aesgcm` won't work (I have not confirmed this).

Are there any plans to add support for aes128gcm? Thanks!

**Comment by martijndwars** [comment]
There were no plans, but I'd be happy to port this to the Java version once I find some time.

**Comment by ghys** [comment]
After some further investigation, I managed to make Edge receive notifications. The Microsoft push server does in fact support `aesgcm`,

I'll leave my troubleshooting steps here for reference:
- the 400 Bad Request was my fault (I had replaced Apache HTTP Client by JAX-RS and was sending headers wrong, but not wrong enough to make Chrome and Firefox fail ;)), after fixing this there was a `401 Unauthorized` error. The detailed error description can actually be found in the push response's header (`WWW-Authenticate: Bearer error="invalid_request",error_description="Malformed Crypto-Key Value"`)
- the trick was to remove the `keyid=p256dh;` part from the Encryption and Crypto-Key headers:
https://github.com/web-push-libs/webpush-java/blob/f5601e5ac93b5a1f790bdc534b678030e8e43d25/src/main/java/nl/martijndwars/webpush/PushService.java#L171-L172

Not sure if I should close this issue, supporting aes128gcm is still desirable since aesgcm will eventually be deprecated (see https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/SX9_nZ1NHy8). I'll leave it up to you :)

Thanks.

**Comment by martijndwars** [comment]
Let's leave the issue open, aes128gcm should be supported at some point.

> the trick was to remove the keyid=p256dh; part from the Encryption and Crypto-Key headers:

Are you saying Edge supports aesgcm, but only when you remove `keyid=p256dh;`? This sounds like something that needs fixing as well..

> The detailed error description can actually be found in the push response's header (WWW-Authenticate: Bearer error="invalid_request",error_description="Malformed Crypto-Key Value")

This is new to me, but sounds super useful. Thanks for sharing!

**Comment by ghys** [comment]
> Are you saying Edge supports aesgcm, but only when you remove keyid=p256dh;?

Correct. I found out the notifications sent by the node library didn't include those and worked, and it was the only difference. I have also confirmed Google and Mozilla's servers are fine without it as well.

**Comment by fatihcoskun79** [comment]
We noticed a sudden increase of this `401 Unauthorized` error from microsoft endpoints yesterday. I assume that something changed that made the webpush feature available to a wider range of Edge users.

**Comment by fatihcoskun79** [comment]
Is there any update on fixing this problem?

**Comment by martijndwars** [comment]
Not from my side, sorry. I haven't had time to look into this yet.

**Comment by fatihcoskun79** [comment]
Is there a known downside to the fix described by @ghys ?

**Comment by oxc** [comment]
See https://github.com/web-push-libs/web-push/issues/234 for removal from the Node.js library.

**Comment by maxpiepenbrink** [comment]
Thanks for this, I ran into this today and this Github link is what saved me. I wish we had a better explanation as to why microsoft's endpoint seems to care about this value.
