### ISSUE TITLE
Send notifications to a large number of subscribers

### ISSUE THREAD

**Issue by spinneret** [web-push-libs/webpush-java#54]
For sending notifications to multiple subscribers, I assume that we would have to create a single instance of PushService and many instances of Notification in a loop, is that correct?

If so, is it practical to send notifications to a very large number of subscribers using the above method? Are there any performance implications? Would this be highly memory or CPU intensive? 

Would it make more sense to split the notifications into batches and run them separately? If so, what would be a good rule of thumb for each batch size? 

Thanks!

**Comment by martijndwars** [comment]
> For sending notifications to multiple subscribers, I assume that we would have to create a single instance of PushService and many instances of Notification in a loop, is that correct?

Correct.

> If so, is it practical to send notifications to a very large number of subscribers using the above method? Are there any performance implications? Would this be highly memory or CPU intensive?

I have no experience with sending messages to a large number of subscribers. If you find concrete ways to improve this library's performance I'd love to hear so. The bottleneck will probably in sending the messages to the browser vendors (Google, Mozilla, etc), so it's neither memory nor CPU intensive but rather I/O bound.

> Would it make more sense to split the notifications into batches and run them separately? If so, what would be a good rule of thumb for each batch size?

I cannot give you any advice on this front other than to try and see where things go wrong. Do keep track of which notifications were sent successfully so you can send the remaining notifications in the subsequent batch.

**Comment by spinneret** [comment]
Thank you for your response! I will run it in a single batch initially and let you know if there are any issues with the code or suggestions to improve performance. Thanks again.
