### ISSUE TITLE
Consider rewriting library API.

### ISSUE THREAD

**Issue by GeorgeTailor** [web-push-libs/webpush-java#56]
1) At the current state the library uses obsolete GCM;
2) API is not well written:

> a) Not able to use API objects as params for web controller (which in most cases uses jackson and not gson)
> b) Having to write custom dto objects introduces name clashes (Subscription, Notification etc.)
> c) Having generated VAPID public key and private key I also have to provide subject, which should be optional as per https://tools.ietf.org/html/rfc7519#page-9.

P.S.:
```
SubscriptionKeys sk = originalSub.getKeys();
nl.martijndwars.webpush.Subscription.Keys keys = new nl.martijndwars.webpush.Subscription().new Keys(sk.getP256dh(), sk.getAuth());
nl.martijndwars.webpush.Subscription sub = new nl.martijndwars.webpush.Subscription();
sub.endpoint = originalSub.getEndpoint();
sub.keys = keys;
```
This is not flexible and is hard to read

**Comment by martijndwars** [comment]
I'll take your feedback into consideration. If you are willing to work on this, I'd be happy to accept a PR that fixes these issues.

**Comment by martijndwars** [comment]
I took another look at your comments. If you directly use the `Notification` class you are not bothered by GSON, avoid name clashes with data transfer classes, and avoid hard-to-read code.

```
Notification notification = new Notification(endpoint, userPublicKey, userAuth, payload);
PushService pushService = new PushService(publicKey, privateKey, subject);
pushService.send(notification);
```

I agree we should make the VAPID subject optional (again, PRs are much appreciated). If you have any other suggestions on how to make the API better, please let me know.
