### ISSUE TITLE
Couldnt build on Java 9/10

### ISSUE THREAD

**Issue by arvindkumarc** [web-push-libs/webpush-java#59]
The following method is not found and fails at runtime.

org.bouncycastle.util.BigIntegers.fromUnsignedByteArray

**Comment by martijndwars** [comment]
Could you provide some more information, such as how you build the project and the error you get at runtime? Note that if your project has a dependency on webpush-java you _also_ need to include a dependency on BouncyCastle.

**Comment by arvindkumarc** [comment]
```
    compile group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.46'
    compile group: 'nl.martijndwars', name: 'web-push', version: '3.1.0'
```

are my gradle dependencies.

I'm using OpenJDK

```17:17 $ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)
```

I tried running it using a Unit Test, with BouncyCastle added as a SecurityProvider. But, I got the above error at runtime at line ` pushService.privateKey = Utils.loadPrivateKey(vapidPrivateKey)`

**Comment by martijndwars** [comment]
I setup Travis to test on openjdk8, openjdk11, oraclejdk8, oraclejdk11. Build [#157](https://travis-ci.org/web-push-libs/webpush-java/builds/475830129) passes on all versions. Any chance you could create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) demonstrating your problem?

**Comment by martijndwars** [comment]
Closing due to lack of response.
