### ISSUE TITLE
Version 3.1.1 not found in Maven

### ISSUE THREAD

**Issue by sherpc** [web-push-libs/webpush-java#61]
Hello,

Could you please push latest version (3.1.1) to Maven?

https://mvnrepository.com/artifact/nl.martijndwars/web-push the last one is 3.1.0.

Thanks!

**Comment by martijndwars** [comment]
Thanks for the heads up, fixed now: http://search.maven.org/#artifactdetails%7Cnl.martijndwars%7Cweb-push%7C3.1.1%7Cjar
