### ISSUE TITLE
Remove guava dependency if not needed

### ISSUE THREAD

**Issue by fischermatte** [web-push-libs/webpush-java#66]
webpush-java has a dependency to guava, which obviously doesn't serve a valid purpose:

    // Not sure what for..
    compile group: 'com.google.guava', name: 'guava', version: '19.0'

since guava is a quite heavy lib (around 3mb), it would be nice to remove this dependency.

**Comment by fischermatte** [comment]
just found the purpose - it is used in several places for base64 encoding: see `com.google.common.io.BaseEncoding`. so removing means a little more effort :-( if i find some time i will provide a pull request. the comment above could be updated...

**Comment by martijndwars** [comment]
Thanks! I suppose it won't be too hard to implement base64 encoding ourselves. If this means we can get rid of the dependency, then I'm all for it. Let me know if you need some help.

**Comment by fischermatte** [comment]
@MartijnDwars before i provide a pull reques - 2 questions: 

1. master branch build is currently broken. did you already have a look at this?
2. is the target jdk version still 7? travis runs against jdk8.

**Comment by martijndwars** [comment]
1. The integration tests use Selenium but we've been seeing some intermittent failures. Don't worry too much about the build being broken. I'll try to fix it this weekend.

2. I'd like to keep targeting Java 7 as there are some people who cannot upgrade to Java 8. I will add a variant for Java 7 to Travis, thanks.

**Comment by martijndwars** [comment]
Fixed in #68, thanks again @fischermatte!
