### ISSUE TITLE
VAPID support

### ISSUE THREAD

**Issue by mohamedhafez** [web-push-libs/webpush-java#7]
If this library could be updated to support VAPID, and the documentation updated to include an example, that would be great:)

**Comment by martijndwars** [comment]
Thanks for the suggestion, I'll look into VAPID this weekend and update the docs. 👍

**Comment by martijndwars** [comment]
Version 2.0.0 released with VAPID support.

**Comment by MartijnDwars** [comment]
Version 2.0 released with VAPID support.
