### ISSUE TITLE
GCM not working without valid VAPID keys

### ISSUE THREAD

**Issue by CKPalk** [web-push-libs/webpush-java#73]
Since updating from 3.0.1 to 4.0.0 we are getting errors when sending GCM notifications. We were able to send them without supplying valid keys before but it's now failing on this assertion.

https://github.com/web-push-libs/webpush-java/blob/87f24810bed3aea778f8597f638794c0add12e5b/src/main/java/nl/martijndwars/webpush/PushService.java#L173-L174

**Comment by CKPalk** [comment]
I would continue using v3.0.1 but I'm unable to successfully send VAPID notifications in this version. 
The assertion above looks to be in all versions past 3.0.1.

**Comment by martijndwars** [comment]
Sorry for the delay. This should be fixed now. In a few hours you will find version 5.0.1 of this library on Maven Central. Let me know if there are any other issues.

**Comment by CKPalk** [comment]
Great, thank you!
