### ISSUE TITLE
Please use aes128gcm as the default encoding.

### ISSUE THREAD

**Issue by jrconlin** [web-push-libs/webpush-java#75]
First off, thanks for this library.

RFC 8188 has been out for over a year, and some clients may soon no longer support the older "aesgcm" encoding format. Can you please make the default "aes128gcm"? Thanks!

**Comment by martijndwars** [comment]
Thanks for the heads up. Making aes128gcm the new default sounds like a reasonable thing to do. I'll try to get a PR out by tomorrow.
