### ISSUE TITLE
Which BouncyCastle version are you using in the example?

### ISSUE THREAD

**Issue by leonchaves** [web-push-libs/webpush-java#80]
Hello, 

Nice work with the api, but I'm facing some problems: your Subscription.getUserPublicKey method in the example is not compiling for me. The compiler cannont find KeyFactory. I tried to import org.bouncycastle.jce.provider.asymmetric.ec.KeyFactory, but then the getInstance(String,String) is undefined. I tried importing other classes but with similar problems. 

In my build.gradle I am using org.bouncycastle:bcprov-jdk16:1.46 

Which BouncyCastle version should I use and what are the complete import statements, please?

Thanks in advance. 

Leonardo

**Comment by leonchaves** [comment]
I were able to solve this problem: I am using web push 5.0.1 (5.0.2-snapshot was not available in my nexus repository) and bcprov-jdk15on v. 1.60. My imports are:

import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PublicKey;
import java.security.Security;
import java.security.spec.InvalidKeySpecException;
import java.util.Base64;
import java.util.HashMap;
import java.util.concurrent.ExecutionException;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.bouncycastle.jce.ECNamedCurveTable;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.jce.spec.ECNamedCurveParameterSpec;
import org.bouncycastle.jce.spec.ECPublicKeySpec;
import org.bouncycastle.math.ec.ECPoint;

And now it compiles. I got another execution error, but I'll post about it in another separate issue if I am not able to solve it.

Thanks.

Leonardo

**Comment by martijndwars** [comment]
The master branch always points to the development version, which is a `-SNAPSHOT` version that is not published to a public repository. The latest stable release is indeed [5.0.1](https://search.maven.org/search?q=g:nl.martijndwars%20a:web-push), which is published to Maven Central. The corresponding BouncyCastle version can be found in [build.gradle](https://github.com/web-push-libs/webpush-java/blob/5.0.1/build.gradle#L33).

Feel free to open a separate issue for any other problems you're having and I'll be happy to have a look.

**Comment by leonchaves** [comment]
Thank you!
