### ISSUE TITLE
Generate Vapid Key Exception

### ISSUE THREAD

**Issue by MuratKaragozgil** [web-push-libs/webpush-java#82]
Hello, 

I want to use generate vapid key method, but everytime i get these stacktrace on server. But I tried on my local machine, its working. I don't know what is different. (JDK and bouncycastyle version are same on local and server)

I have already tried different JDK and BouncyCastyle versions but nothing changed.

My code is here;

```Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
	GenerateKeyHandler generateKeyHandler = new GenerateKeyHandler(new GenerateKeyCommand());
	KeyPair vapidKeys = generateKeyHandler.generateKeyPair();

	ECPublicKey publicKey = (ECPublicKey) vapidKeys.getPublic();
	ECPrivateKey privateKey = (ECPrivateKey) vapidKeys.getPrivate();

	byte[] encodedPublicKey = Utils.encode(publicKey);
	byte[] encodedPrivateKey = Utils.encode(privateKey);

	String publicVapidKey = Base64Encoder.encodeUrl(encodedPublicKey);
	String privateVapidKey = Base64Encoder.encodeUrl(encodedPrivateKey);
```

Stacktrare is here ;

```java.security.InvalidAlgorithmParameterException: parameter object not a ECParameterSpec
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyPairGeneratorSpi$EC.initialize(Unknown Source)
	at java.security.KeyPairGenerator.initialize(KeyPairGenerator.java:411)
	at nl.martijndwars.webpush.cli.handlers.GenerateKeyHandler.generateKeyPair(GenerateKeyHandler.java:63)
```

**Comment by martijndwars** [comment]
1. To troubleshoot this problem, I'd need to see the full stack trace. Can you post this? The start of the stack trace should show which exception is being thrown.

2. Alternatively, you can generate a key pair online at https://web-push-codelab.glitch.me/. This page generates a public- and private key and encodes them using base64. You can configure the Java library to use the base64 strings.

**Comment by martijndwars** [comment]
I'm closing this issue. Feel free to leave a comment if you still have an issue.
