### ISSUE TITLE
Query To Send Push Notification to Multiple endpoints either in loop Or Batch

### ISSUE THREAD

**Issue by aaravrahul3268** [web-push-libs/webpush-java#88]
I have Implemented the code for calling this push library and its working for one endpoint . but I want to know the way to send to multiple endponts at a time.

**Comment by martijndwars** [comment]
The simplest solution is to loop over your notifications and repeat the call to `pushService.send(notification)`. Endpoints have different addresses and with VAPID each message needs to be encrypted with the user's public key, so there's not much room for batching.
