### ISSUE TITLE
Please specify third party libraries

### ISSUE THREAD

**Issue by ghost** [web-push-libs/webpush-java#93]
I have doubt using Bouncy Castle library as it is throwing error"InvalidAlgorithmParameter  Exception: unknown parameter type".
So I was using Bouncy Castle version 1.49 with JDK 12.
Can you please specify the version of bouncy castle that you were using.

https://stackoverflow.com/questions/42928339/gcmparameterspec-throws-invalidalgorithmparameterexception-unknown-parameter-ty
http://shibboleth.net/pipermail/users/2016-July/030322.html 

These may help!

**Comment by martijndwars** [comment]
The project is currently using version 1.54 ([source](https://github.com/web-push-libs/webpush-java/blob/5e2cff7c90fec84cc04498037bebebbe1aab0b97/build.gradle#L33)). Let me know if you need further help.
