### ISSUE TITLE
Dont work in Java Version 7 Error: NoSuchMethodError- org.bouncycastle.math.ec.ECPoint.getEncoded()

### ISSUE THREAD

**Issue by dherediat97** [web-push-libs/webpush-java#95]
Hello,

the newer version dont work  for me(different configurations) in JAVA 7.

Java Version: JAVA 7

Dependencies in pom.xml

```
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
     <version>1.54</version>
</dependency>

<dependency>
    <groupId>nl.martijndwars</groupId>
    <artifactId>web-push</artifactId>
    <version>5.0.2</version>
</dependency>

```
Code(I also tried the request web push way and also dont work, the error was  this [InvalidKeyException: ECDH key agreement requires ECPublicKey for doPhase](https://stackoverflow.com/questions/35228063/encrypt-message-for-web-push-api-in-java)):
```
if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null){
    Security.addProvider(new BouncyCastleProvider());
}
int TTL = 255;
PushService pushService= new PushService();
KeyFactory kf = KeyFactory.getInstance("ECDH", BouncyCastleProvider.PROVIDER_NAME);
ECNamedCurveParameterSpec ecSpec = ECNamedCurveTable.getParameterSpec("secp256r1");
String key = jsonSubscription.getString("key");
String auth = jsonSubscription.getString("auth");
                           
ECPoint point = ecSpec.getCurve().decodePoint(Base64.getDecoder().decode(key));
ECPublicKeySpec pubSpec = new ECPublicKeySpec(point, ecSpec);
PublicKey userPublicKey = kf.generatePublic(pubSpec);
byte[] userAuth = Base64.getDecoder().decode(auth);
Notification notification = new Notification(
                                   url, 
                                   userPublicKey, 
                                   userAuth, 
                                   mensajeAdmin.getBytes(),
                                   TTL);
pushService.setGcmApiKey(authKeyFCM);
pushService.send(notification);
```

Log Trace:
```
java.lang.NoSuchMethodError: org.bouncycastle.math.ec.ECPoint.getEncoded(Z)[B
	at nl.martijndwars.webpush.Utils.encode(Utils.java:34)
	at nl.martijndwars.webpush.HttpEce.lengthPrefix(HttpEce.java:400)
	at nl.martijndwars.webpush.HttpEce.extractDH(HttpEce.java:364)
	at nl.martijndwars.webpush.HttpEce.extractSecretAndContext(HttpEce.java:229)
	at nl.martijndwars.webpush.HttpEce.deriveKeyAndNonce(HttpEce.java:256)
	at nl.martijndwars.webpush.HttpEce.encrypt(HttpEce.java:70)
	at nl.martijndwars.webpush.PushService.encrypt(PushService.java:95)
	at nl.martijndwars.webpush.PushService.preparePost(PushService.java:176)
	at nl.martijndwars.webpush.PushService.sendAsync(PushService.java:151)
	at nl.martijndwars.webpush.PushService.send(PushService.java:133)
	at nl.martijndwars.webpush.PushService.send(PushService.java:137)
```
Code of Utils.java:34 :

```
public static byte[] encode(ECPublicKey publicKey) {
     return publicKey.getQ().getEncoded(false);
}
```
Related post in stackoverflow:[https://stackoverflow.com/questions/43943374/java-getencoded-nosuchmethoderror]( https://stackoverflow.com/questions/43943374/java-getencoded-nosuchmethoderror)

The web part to register the subscription is based in the wiki of this [repo](https://github.com/web-push-libs/webpush-java/wiki/Usage-Example).

If the solution is change the Java version to a version more older,i can't do that.

Greetings @dherediat97

**Comment by martijndwars** [comment]
Your strack trace indicates that you have a different version of BouncyCastle on your classpath. BouncyCastle 1.54 contains a `byte[] getEncoded(boolean)` method, as becomes evident by the following trace:

```
martijn@dhcp-10-174-225-146:~$ javap -cp ~/Downloads/bcprov-jdk15on-1.54.jar org.bouncycastle.math.ec.ECPoint | grep 'getEncoded'
  public byte[] getEncoded();
  public byte[] getEncoded(boolean);
```

Is there a way to verify your runtime classpath? Can you check if BouncyCastle 1.54 is really on there, or if some other version is being used? Or can you share how you run your Java application?

**Comment by dherediat97** [comment]
I go to try know the version of bouncycastle in execution...

log.debug("Version Bouncy Castle")
                           log.debug(org.bouncycastle.jce.provider.BouncyCastleProvider
                           .class
                           .getPackage()
                           .getImplementationVersion());

![imagen](https://user-images.githubusercontent.com/17063135/64119480-40f58280-cd9a-11e9-83a0-d4afc56df0ec.png)

If is different of 1.54, i remove the dependency of bouncy castle of the others parent projects or  do that the dependecy of bouncy castle of this proyect be more important than the others.

I saw before the method (by clicking inside) with eclipse but, of course, I don't know what version it was

Greetings @dherediat97

**Comment by dherediat97** [comment]
Now the problem is with apache commons codec, and the same problem or  similar problem:

`java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString([B)Ljava/lang/String;`

**Comment by dherediat97** [comment]
Solved, Thanks you @MartijnDwars
