### ISSUE TITLE
Support for BouncyCastle bcprov-jdk16?

### ISSUE THREAD

**Issue by dherediat97** [web-push-libs/webpush-java#97]
Hello,

my question is:

is possible that this library have support for bcprov-jdk16(Bouncy Castle)?

The method BigIntegers.fromUnsignedByteArray of bouncy castle dont exists in bcprov-jdk16 but yes in bcprov-jdk15on.

I know that i open and closed a related issue about this (https://github.com/web-push-libs/webpush-java/issues/95) but is different i think.

Greetings @dherediat97

**Comment by martijndwars** [comment]
We'd have to check the implications of upgrading BouncyCastle. For the call to `BigIntegers.fromUnsignedByteArray`, the [implementation](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/util/BigIntegers.java#L111-L114) does nothing special. We might as well inline the creation of the `BigInteger` and remove the call into BouncyCastle. Would that already solve your problem?

**Comment by dherediat97** [comment]
Yes @MartijnDwars, 

is very possible(i am 100% sure that are more errors or not, because when i change the version the first error is that, but if only is this is solved , but i dont know if there are more errors after).

Sorry for the delay.

greetings @dherediat97

**Comment by mchiba52** [comment]
The inline will help as I am getting an error on java.math.BigInteger that is called from the BC function BigIntegers.fromUnsignedByteArray
